name: pr-closed
concurrency: ${{ github.event.number }}

on:
  pull_request:
    types:
      - "closed"

env:
  resourceGroupName: pr_${{ github.event.number }}

jobs:
  remove:
    runs-on: ubuntu-latest
    steps:
      - name: Sign in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Delete resource group
        uses: azure/cli@v1
        with:
          inlineScript: |
            az group delete \
              --name ${{ env.resourceGroupName }} \
              --yes
              